name: CI
on:
  - push
env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  CL: /source-charset:.949 /execution-charset:.949
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v1
      - working-directory: ${{env.GITHUB_WORKSPACE}}
        run: >-
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} 
          ${{env.SOLUTION_FILE_PATH}}
      - run: echo "filename=${GITHUB_REPOSITORY#*/}-${GITHUB_REF##*/}.zip" >> $GITHUB_OUTPUT
        shell: bash
        id: zip
      - uses: vimtor/action-zip@v1.1
        with:
          files: Release/ddraw.dll
          dest: ${{steps.zip.outputs.filename}}
      - uses: actions/upload-artifact@v3
        with:
          path: ${{steps.zip.outputs.filename}}
    outputs:
      filename: ${{steps.zip.outputs.filename}}
  release:
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v3
      - uses: tubone24/update_release@v1.3.1
        id: update_release
        env:
          GITHUB_TOKEN: ${{github.token}}
      - uses: tanyagray/action-upload-release-asset@v1.1.3
        env:
          GITHUB_TOKEN: ${{github.token}}
        with:
          upload_url: ${{steps.update_release.outputs.upload_url}}
          asset_path: artifact/${{needs.build.outputs.filename}}
          asset_name: ${{needs.build.outputs.filename}}
          asset_content_type: application/zip
